### ISSUE TITLE
Flatpak warns of unsupported platform

### ISSUE THREAD

**Issue by vwbusguy** [endlessm/eos-photos#327]
This app depends on the end-of-life 3.36 version of Gnome.  When updating flatpak, I always see this warning with this app installed:

```
$ flatpak update
Looking for updates…
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.endlessm.photos
```

**Comment by bbhtt** [comment]
Hi, I opened https://github.com/flathub/com.endlessm.photos/pull/8 that updates the runtime and the dependencies. If the developers gave a review, it'd be great. Also, if you still use this, it'd be great if you can test the posted build there and let me know if everything works there.

**Comment by vwbusguy** [comment]
Looks like your PR there fixed it!
